// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfy8-sulZVbQZxEaqizkmVP_rNUuc4RRs',
    appId: '1:1060365432356:web:ecf16d6b51903dc72d4ab1',
    messagingSenderId: '1060365432356',
    projectId: 'medhasvini-87d7b',
    authDomain: 'medhasvini-87d7b.firebaseapp.com',
    storageBucket: 'medhasvini-87d7b.appspot.com',
    measurementId: 'G-K7BJ8JGGZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9zJdmD-y87NX4LKyd6n2-10ZWm2Gz_OI',
    appId: '1:1060365432356:android:5befee6ee94554b42d4ab1',
    messagingSenderId: '1060365432356',
    projectId: 'medhasvini-87d7b',
    storageBucket: 'medhasvini-87d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB0gBEjM_KOBn5nT6EAulSQ_JteaGp624',
    appId: '1:1060365432356:ios:0548cccfd4df538f2d4ab1',
    messagingSenderId: '1060365432356',
    projectId: 'medhasvini-87d7b',
    storageBucket: 'medhasvini-87d7b.appspot.com',
    iosBundleId: 'com.ridgeant.medhasvinieducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB0gBEjM_KOBn5nT6EAulSQ_JteaGp624',
    appId: '1:1060365432356:ios:aa3dcf825c45e1082d4ab1',
    messagingSenderId: '1060365432356',
    projectId: 'medhasvini-87d7b',
    storageBucket: 'medhasvini-87d7b.appspot.com',
    iosBundleId: 'com.ridgeant.medhasvinieducation.RunnerTests',
  );
}
